<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 2021/11/30
 * Time: 15:19
 */
namespace app\common\controller;
use think\Controller;

class Base extends  Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        header('Access-Control-Allow-Origin: *');
        header("Access-Control-Allow-Headers:Origin, X-Requested-With, Content-Type, Accept");
        header('Access-Control-Allow-Methods: POST,GET');
        if(request()->isOptions()){
            exit();
        }
    }
}